// Code generated by hertz generator.

package goods

import (
	"NihiStore/server/cmd/api/config"
	"NihiStore/server/shared/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return nil
}

func _goodsMw() []app.HandlerFunc {
	return nil
}

func _creategoodsMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.JWTAuthMiddleware(config.GlobalServerConfig.JWTInfo.SigningKey),
	}
}

func _deletegoodsMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.JWTAuthMiddleware(config.GlobalServerConfig.JWTInfo.SigningKey),
	}
}

func _searchgoodsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchgoodsinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updategoodsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _alipayMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _buygoodsMw() []app.HandlerFunc {
	// your code...
	return nil
}
