// Code generated by hertz generator.

package goods

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _goodsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _creategoodsMw() []app.HandlerFunc {
	// your code...
	return nil
}
