// Code generated by hertz generator.

package goods

import (
	hgoods "NihiStore/server/cmd/api/biz/model/goods"
	kgoods "NihiStore/server/shared/kitex_gen/goods"
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateGoods .
// @router /goods/creat [POST]
func CreateGoods(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hgoods.CreateGoodsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	c.Get("Is")
	resp := new(kgoods.CreateGoodsResponse)
	c.JSON(200, resp)
	return
}
