// Code generated by hertz generator.

package goods

import (
	hgoods "NihiStore/server/cmd/api/biz/model/goods"
	"NihiStore/server/cmd/api/config"
	"NihiStore/server/cmd/api/pkg"
	"NihiStore/server/shared/errx"
	kgoods "NihiStore/server/shared/kitex_gen/goods"
	"NihiStore/server/shared/tools"
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"net/http"
)

// CreateGoods .
// @router /goods/creat [POST]
func CreateGoods(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hgoods.CreateGoodsReq
	resp := new(kgoods.CreateGoodsResponse)
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	auth, _ := c.Get("IsSeller")
	ID, _ := c.Get("ID")
	if auth.(bool) != true {
		resp.BaseResp = tools.BuildBaseResp(errx.AuthCreatGoodsFail, "Auth seller failed")
		c.JSON(errx.AuthSellerFail, resp)
		return
	}
	resp, err = config.GlobalGoodsClient.CreateGoods(ctx, &kgoods.CreateGoodsRequest{
		Id:               ID.(int64),
		GoodsInformation: pkg.ConvertGoodsInformation(req.GoodsInformation),
	})

	if err != nil {
		hlog.Error("rpc user service err!", err)
		c.JSON(http.StatusInternalServerError, resp)
		return
	}

	c.JSON(200, resp)
	return
}

// DeleteGoods .
// @router /goods/delete [DELETE]
func DeleteGoods(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hgoods.DeleteGoodsReq
	resp := new(kgoods.DeleteGoodsResponse)
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	auth, _ := c.Get("IsSeller")
	ID, _ := c.Get("ID")
	if auth.(bool) != true {
		resp.BaseResp = tools.BuildBaseResp(errx.AuthCreatGoodsFail, "Auth seller failed")
		c.JSON(errx.AuthSellerFail, resp)
		return
	}
	resp, err = config.GlobalGoodsClient.DeleteGoods(ctx, &kgoods.DeleteGoodsRequest{
		GoodsId:  req.GoodsId,
		SellerId: ID.(int64),
	})

	if err != nil {
		hlog.Error("rpc user service err!", err)
		c.JSON(http.StatusInternalServerError, resp)
		return
	}

	c.JSON(200, resp)
	return
}

// SearchGoodsInfo .
// @router /goods/searchgoodsinfo [GET]
func SearchGoodsInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hgoods.SearchGoodsInfoReq
	resp := new(kgoods.SearchGoodsInfoResponse)
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp, err = config.GlobalGoodsClient.SearchGoodsInfo(ctx, &kgoods.SearchGoodsInfoRequest{
		SearchMsg:  req.SearchMsg,
		Page:       req.Page,
		PageAmount: req.PageAmount,
	})
	if err != nil {
		hlog.Error("rpc user service err!", err)
		c.JSON(http.StatusInternalServerError, resp)
		return
	}

	c.JSON(200, resp)
	return
}

// SearchGoods .
// @router /goods/searchgoods [GET]
func SearchGoods(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hgoods.SearchGoodsReq
	resp := new(kgoods.SearchGoodsResponse)
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp, err = config.GlobalGoodsClient.SearchGoods(ctx, &kgoods.SearchGoodsRequest{Id: req.GoodsId})
	if err != nil {
		hlog.Error("rpc user service err!", err)
		c.JSON(http.StatusInternalServerError, resp)
		return
	}
	c.JSON(200, resp)
	return
}

// UpdateGoods .
// @router /goods/update [PUT]
func UpdateGoods(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hgoods.UpdateGoodsReq
	resp := new(kgoods.UpdateGoodsResponse)
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	auth, _ := c.Get("IsSeller")
	ID, _ := c.Get("ID")
	if auth.(bool) != true {
		resp.BaseResp = tools.BuildBaseResp(errx.AuthCreatGoodsFail, "Auth seller failed")
		c.JSON(errx.AuthSellerFail, resp)
		return
	}
	resp, err = config.GlobalGoodsClient.UpdateGoods(ctx, &kgoods.UpdateGoodsRequest{
		Id:               req.ID,
		GoodsInformation: pkg.ConvertGoodsInformation(req.GoodsInformation),
		UserId:           ID.(int64),
	})
	if err != nil {
		hlog.Error("rpc user service err!", err)
		c.JSON(http.StatusInternalServerError, resp)
		return
	}
	c.JSON(200, resp)
	return
}

// UploadGoodsPhoto .
// @router /goods/uploadgoodsphoto [GET]
func UploadGoodsPhoto(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hgoods.UploadGoodsPhotoReq
	resp := new(kgoods.UploadGoodsPhotoResponse)
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp, err = config.GlobalGoodsClient.UploadGoodsPhoto(ctx, &kgoods.UploadGoodsPhotoRequest{GoodsId: req.GoodsId})
	if err != nil {
		hlog.Error("rpc user service err!", err)
		c.JSON(http.StatusInternalServerError, resp)
		return
	}
	c.JSON(200, resp)
	return
}

// GetGoodsPhoto .
// @router /goods/getgoodsphoto [GET]
func GetGoodsPhoto(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hgoods.GetGoodsPhotoReq
	resp := new(kgoods.GetGoodsPhotoResponse)
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp, err = config.GlobalGoodsClient.GetGoodsPhoto(ctx, &kgoods.GetGoodsPhotoRequest{GoodsId: req.GoodsId})
	if err != nil {
		hlog.Error("rpc user service err!", err)
		c.JSON(http.StatusInternalServerError, resp)
		return
	}
	c.JSON(200, resp)
	return
}
