// Code generated by Kitex v0.5.1. DO NOT EDIT.

package payservice

import (
	pay "NihiStore/server/shared/kitex_gen/pay"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	BuyGoods(ctx context.Context, req *pay.BuyGoodsRequest, callOptions ...callopt.Option) (r *pay.BuyGoodsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPayServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPayServiceClient struct {
	*kClient
}

func (p *kPayServiceClient) BuyGoods(ctx context.Context, req *pay.BuyGoodsRequest, callOptions ...callopt.Option) (r *pay.BuyGoodsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BuyGoods(ctx, req)
}
