// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	goods "NihiStore/server/cmd/api/biz/router/goods"
	user "NihiStore/server/cmd/api/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	goods.Register(r)

	user.Register(r)
}
