// Code generated by hertz generator.

package user

import (
	"context"

	huser "NihiStore/server/cmd/api/biz/model/user"
	kuser "NihiStore/server/shared/kitex_gen/user"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Login .
// @router /login [GET]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req huser.LoginReq
	resp := new(kuser.LoginResponse)

	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// Register .
// @router /request [GET]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req huser.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(huser.RegisterResp)

	c.JSON(consts.StatusOK, resp)
}
